name: Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Setup 
      uses: actions/setup-node@v3
      with:
        node-version: '18.14.2'
        cache: 'npm'
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build
    - name: Deploy
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./docs/.vitepress/dist
        cname: vertis.cadgerfeast.dev
